[package]
name = "agent_world_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
agent_world_core = { path = "../agent_world_core" }
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }

ratatui = "0.29.0"
